services:
  auth:
    build: ./backend/auth
    container_name: auth_interview
    env_file:
      - ./backend/auth/.env
    environment:
      DB_HOST: auth-postgres
      DB_PORT: 5432
    ports:
      - "8001:8000"
    volumes:
      - ./backend/auth/migrations:/service/migrations
    depends_on:
      auth-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - auth-network
      - app-shared-network

  interview:
    build: ./backend/interview
    container_name: interview_module
    env_file:
      - ./backend/interview/.env
    environment:
      DB_HOST: interview-postgres
      DB_PORT: 5432
    ports:
      - "8002:8000"
    volumes:
      - ./backend/interview/migrations:/service/migrations
    depends_on:
      interview-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - interview-network
      - app-shared-network

  telegram-bot:
    build: ./telegram-bot
    container_name: telegram_bot
    env_file:
      - ./telegram-bot/.env
    environment:
      AUTH_SERVICE_URL: http://auth:8000
      INTERVIEW_SERVICE_URL: http://interview:8000
    restart: unless-stopped
    depends_on:
      auth:
        condition: service_healthy
      interview:
        condition: service_healthy
    networks:
      - app-shared-network

  auth-postgres:
    image: postgres:16-alpine
    container_name: interview_auth_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - auth-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  interview-postgres:
    image: postgres:16-alpine
    container_name: interview_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: interview_db
    ports:
      - "5434:5432"
    volumes:
        - pgdata_interview:/var/lib/postgresql/data
    networks:
      - interview-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d interview_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_auth:
  pgdata_interview:

networks:
  auth-network:
    driver: bridge
  interview-network:
    driver: bridge
  app-shared-network:
    driver: bridge