"""...

Revision ID: 0bae4f9ae2ae
Revises: 
Create Date: 2026-08-25 09:36:38.420089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bae4f9ae2ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
